version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: yutfut
      POSTGRES_USER: yutfut
      POSTGRES_PASSWORD: yutfut
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - '5432:5432'
    volumes:
      - ./init_db/:/docker-entrypoint-initdb.d/
      - .:/var/lib/postgresql/data/

  adminer:
    image: adminer
    restart: always
    links:
      - "db:db"
    ports:
      - "8090:8080"
    depends_on:
      - db