version: '3.7'

services:
  postgresql:
    image: postgres:latest
    environment:
      POSTGRES_DB: example
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
    ports:
      - '5432:5432'
#     volumes:
#       - ./volumes:/volumes

  # cassandra:
  #   image: cassandra:latest
  #   ports:
  #     - '9042:9042'

  # mongodb:
  #   image: mongo:latest
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=admin
  #     - MONGO_INITDB_ROOT_PASSWORD=admin
  #   ports:
  #     - '27017:27017'

#   neo4j:
#     image: neo4j:latest
#     environment:
#       - NEO4J_AUTH=neo4j/password
#     ports:
#       - "7474:7474"
#       - "7687:7687"